roles = ['cap', 'B1', 'B2', 'B3', 'B4', 'RJC', 'RJL', 'SA_pcp1', 'SA_pcp2',
         'SA_scd', 'SA_remp1', 'SA_remp2', 'drop1', 'drop2', 'drop3']

corres_poste_num = dict(PI = ['n1','n3'],
                        TA = ['n2'],
                        DL = ['n4','n5'],
                        TL = ['n6','n7'],
                        N8 = ['n8'],
                        DM = ['n9'],
                        DO = ['n10'],
                        C1 = ['n12'],
                        C2 = ['n13'],
                        AI = ['n11','n14'],
                        AR = ['n15'])

corres_num_poste = dict(n1 = 'PI',
                        n2 = 'TA',
                        n3 = 'PI',
                        n4 = 'DL',
                        n5 = 'DL',
                        n6 = 'TL',
                        n7 = 'TL',
                        n8 = 'N8',
                        n9 = 'DM',
                        n10 = 'DO',
                        n11 = 'AI',
                        n12 = 'C1',
                        n13 = 'C2',
                        n14 = 'AI',
                        n15 = 'AR',
                        n16 = 'TA',
                        n17 = 'PI',
                        n18 = 'DL',
                        n19 = 'TL N8',
                        n20 = 'DM DO',
                        n21 = 'DO CE AR',
                        n22 = 'AI AR')

ordres_caracs_compo = dict(M=1,
                           OplusAV=2,
                           OplusAR=3,
                           OmoinsAV=4,
                           OmoinsAR=5,
                           ME=6,
                           R=7,
                           TO_def=8,
                           TO_off=9,
                           PA=10,
                           JP=11,
                           A=12,
                           E=13)

ordre_roles = dict(cap=1,
                   B1=2,
                   B2=3,
                   B3=4,
                   B4=5,
                   RJL=6,
                   RJC=7,
                   SA_pcp1=8,
                   SA_pcp2=9,
                   SA_scd=10,
                   SA_remp1=11,
                   SA_remp2=12,
                   drop1=13,
                   drop2=14,
                   drop3=15)

carac_roles = dict(cap='E',
                   B1='TB',
                   B2='TB',
                   B3='TB',
                   B4='TB',
                   RJL='P',
                   RJC='JP',
                   SA_pcp1='TO',
                   SA_pcp2='TO',
                   SA_scd='TO',
                   SA_remp1='TO',
                   SA_remp2='TO',
                   drop1='JP',
                   drop2='JP',
                   drop3='JP')

limite_poste = dict(PI=6,
                    TA=4,
                    DL=6,
                    TL=9,
                    N8=9,
                    DM=3,
                    DO=3,
                    CE=6,
                    AI=5,
                    AR=4,
                    espoirs=15)

ordre_postes = dict()
for i, p in enumerate(['PI', 'TA', 'DL', 'TL', 'N8','DM', 'DO', 'C1', 'C2',
                       'CE', 'AI', 'AR', 'espoirs', 'tous']):
    ordre_postes[p] = i


nb_joueurs_poste = dict(PI=2,
                        TA=1,
                        DL=2,
                        TL=2,
                        N8=1,
                        DM=1,
                        DO=1,
                        C1=1,
                        C2=1,
                        AI=2,
                        AR=1)
